In [1]:
#Logistic Regression one vs rest

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
x,y=make_classification(n_samples=1000,n_features=2,n_redundant=0,n_classes=2,random_state=42)

In [4]:
pd.DataFrame(x)

0         1
0   -0.999102 -0.663860
1    1.246686  1.153597
2    0.962777  0.859397
3   -2.957441  2.033645
4    1.141165  1.059449
..        ...       ...
995 -0.432774  0.890930
996  1.020438  1.164617
997 -0.101267 -1.590176
998  0.643761 -0.780539
999  0.698530 -1.279405

[1000 rows x 2 columns]

In [5]:
pd.DataFrame(y)

0
0    1
1    1
2    1
3    1
4    1
..  ..
995  0
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [7]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((800, 2), (200, 2), (800,), (200,))

In [8]:
from sklearn.linear_model import LogisticRegression
regression=LogisticRegression()
regression.fit(x_train,y_train)
y_predict=regression.predict(x_test)
y_predict

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0])

In [9]:
regression.predict_proba(x_test)

array([[9.84570917e-01, 1.54290830e-02],
       [1.01327809e-02, 9.89867219e-01],
       [1.92461976e-01, 8.07538024e-01],
       [5.23076046e-01, 4.76923954e-01],
       [9.08170054e-01, 9.18299465e-02],
       [6.34715956e-01, 3.65284044e-01],
       [6.17342708e-02, 9.38265729e-01],
       [9.50182872e-02, 9.04981713e-01],
       [8.16721002e-01, 1.83278998e-01],
       [1.26843685e-01, 8.73156315e-01],
       [3.80052355e-02, 9.61994765e-01],
       [9.69924860e-01, 3.00751404e-02],
       [4.65323411e-01, 5.34676589e-01],
       [6.10153026e-02, 9.38984697e-01],
       [3.86249937e-03, 9.96137501e-01],
       [4.94092975e-02, 9.50590703e-01],
       [7.49614071e-02, 9.25038593e-01],
       [4.53951628e-01, 5.46048372e-01],
       [6.86453579e-01, 3.13546421e-01],
       [8.47489498e-01, 1.52510502e-01],
       [3.67008345e-02, 9.63299165e-01],
       [1.88656586e-02, 9.81134341e-01],
       [1.65411025e-02, 9.83458897e-01],
       [3.16215783e-01, 6.83784217e-01],
       [4.242797

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [11]:
score=accuracy_score(y_test,y_predict)
print(score)
confusion=confusion_matrix(y_test,y_predict)
print(confusion)
make=classification_report(y_test,y_predict)
print(make)

0.88
[[89 12]
 [12 87]]
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       101
           1       0.88      0.88      0.88        99

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



In [13]:
penalty : {'l1', 'l2', 'elasticnet'}

In [14]:
#Hyper Paramater Tunning

In [15]:
model=LogisticRegression()

In [16]:
penalty=['l1', 'l2', 'elasticnet']
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
c_Values=[100,10,1.0,0.1,0.01]

In [17]:
paramas=dict(penalty=penalty,C=c_Values,solver=solver)

In [18]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [19]:
model=LogisticRegression()

In [20]:
grid1

NameError: name 'grid1' is not defined

In [69]:
grid1.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [70]:
grid1.best_score_

0.86625

In [71]:
y_pre=grid1.predict(x_test)

In [72]:
score=accuracy_score(y_test,y_pre)
print(score)
confusion=confusion_matrix(y_test,y_pre)
print(confusion)
make=classification_report(y_test,y_pre)
print(make)

0.88
[[91 10]
 [14 85]]
              precision    recall  f1-score   support

           0       0.87      0.90      0.88       101
           1       0.89      0.86      0.88        99

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



In [73]:
#Randomized Search CV

In [74]:
from sklearn.model_selection import RandomizedSearchCV

In [78]:
random= RandomizedSearchCV(estimator=model,param_distributions=paramas,scoring='accuracy',n_jobs=-1,cv=5)

In [79]:
random

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [80]:
random.fit(x_train,y_train)

C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
15 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumar\AppData\Roaming\Python\Python311\site-pa

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [83]:
random.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 0.01}

In [84]:
random.best_score_

0.86

In [85]:
y_p=random.predict(x_test)

In [86]:
score=accuracy_score(y_test,y_p)
print(score)
confusion=confusion_matrix(y_test,y_p)
print(confusion)
make=classification_report(y_test,y_p)
print(make)

0.88
[[93  8]
 [16 83]]
              precision    recall  f1-score   support

           0       0.85      0.92      0.89       101
           1       0.91      0.84      0.87        99

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



#Logistic Regression for multiclass classification problem

In [88]:
from sklearn.datasets import make_classification

In [110]:
x,y=make_classification(n_samples=1000,n_features=10,n_classes=3,random_state=42,n_informative=3)

In [111]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1= train_test_split(x,y,test_size=0.20,random_state=42)

In [112]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((800, 10), (200, 10), (800,), (200,))

In [113]:
from sklearn.linear_model import LogisticRegression

In [114]:
regress=LogisticRegression(multi_class= 'ovr')

In [115]:
regress.fit(x_train,y_train)

C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [116]:
y_pred1=regress.predict(x_test)

In [117]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [118]:
score1=accuracy_score(y_test,y_pred1)
print(score1)
confusion1=confusion_matrix(y_test,y_pred1)
print(confusion1)
print(classification_report(y_test,y_pred1))

0.65
[[49 12  5]
 [25 27 17]
 [ 2  9 54]]
              precision    recall  f1-score   support

           0       0.64      0.74      0.69        66
           1       0.56      0.39      0.46        69
           2       0.71      0.83      0.77        65

    accuracy                           0.65       200
   macro avg       0.64      0.65      0.64       200
weighted avg       0.64      0.65      0.64       200



In [119]:
model=LogisticRegression()

In [120]:
penalty=['l1', 'l2', 'elasticnet']
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
c_Values=[100,10,1.0,0.1,0.01]

In [121]:
paramas=dict(penalty=penalty,C=c_Values,solver=solver)

In [128]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold(n_splits=3)

In [129]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=paramas,scoring='accuracy',n_jobs=1,cv=cv)

In [130]:
grid.fit(x_train1,y_train1)

C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\svm\_base.py:1243: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\svm\_base.py:1243: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\kumar\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\kumar\AppData\Roam

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [131]:
y_predict1=grid.predict(x_test)

In [132]:
score1=accuracy_score(y_test,y_predict1)
print(score1)
confusion1=confusion_matrix(y_test,y_predict1)
print(confusion1)
print(classification_report(y_test,y_predict1))

0.685
[[50 11  5]
 [22 30 17]
 [ 2  6 57]]
              precision    recall  f1-score   support

           0       0.68      0.76      0.71        66
           1       0.64      0.43      0.52        69
           2       0.72      0.88      0.79        65

    accuracy                           0.69       200
   macro avg       0.68      0.69      0.67       200
weighted avg       0.68      0.69      0.67       200

